### ISSUE TITLE
Incorrect output when using serde tags

### ISSUE THREAD

**Issue by d4hines** [oscartbeaumont/specta#214] opened 2024-01-31 20:13 UTC
Hello,
I noticed that when using `#[serde(tag = ...)]` like so: 
```rust
#[derive(Type)]
#[serde(tag = "type")]
pub enum MyEnum {
    A(Option<MyStruct>),
    B,
}
```
the outputted type is incorrect.

I've created a small reproducer [here](https://github.com/d4hines/specta-serde-bug/blob/master/src/main.rs) that makes the following output. On the left is actual, right is what I expect:
```
assertion `left == right` failed
  left: "export type MyEnum = ({ type: \"A\" } & MyStruct | null) | { type: \"B\" }"
 right: "export type MyEnum = ({ type: \"A\" } & (MyStruct | null)) | { type: \"B\" }"
 ```
 
 I'm not sure if this serde features is supported yet, but figured I'd report here anyway.

**Comment by d4hines** [comment] 2024-01-31 20:17
The issue seems to be that `&` binds tighter than `|` and the printer isn't accounting for that (incidentally, can't even find a Typescript type operator precedence table with google :man_shrugging:). Maybe inserting parens on around `|` would be a sufficient fix?

**Comment by d4hines** [comment] 2024-01-31 21:35
This seems like a hack, but it works for our use case: https://github.com/d4hines/specta/commit/b280b6a03507e23fcb60abdfb59171fce4cc2078

**Comment by oscartbeaumont** [comment] 2024-02-05 02:40
Great spot but from the looks of it this is a duplicate of #174 & https://github.com/oscartbeaumont/specta/commit/467e2b083c802086da2c2b9caeced1509d4a0000 which have been fixed on Specta v2.

However, it's worth noting your type also doesn't parse the new Serde validation built into Specta v2 so you may have problems just upgrading. This extra checking will be optional for final release but right now it's required (#217).

You can checkout this Rust playground to see the runtime errors Serde would spit out: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=34f9c718cf77f18e8d47ade4e6d76ea5

**Closed by oscartbeaumont** 2024-02-05 02:40 UTC
